### ISSUE TITLE
Couple Build Questions

### ISSUE THREAD

**Issue by MrMonotone** [nothings/obbg#10]
I was trying to build obbg on Solus Linux. I have got it to build but before I submit a pull request I have a few questions.

* The application is built using SDL2 correct? (I built it with SDL2 but I do not know the difference between the two.) The current make file was using SDL1 network files. I changed it to use SDL2.

* I had to change a couple of the includes to make them work on Linux. How should I handle those in the pull request? A lot of them were just adding a folder because Linux sorts its includes into folders e.g. SDL/SDL2.h

* Do you mind if I add build instructions to the readme or a building file or something?

* On a sidenote, Do you check your github email I have some other questions that do not really fit an issue that I would like to ask you.

Thanks for the excellent libraries and examples!

**Comment by nothings** [comment]
It uses SDL2, yes.

If you want to tweak the includes, I'd wrap them in an #ifdef so the existing behavior is unchanged.

You can put linux build instructions in a separate file (maybe something along the lines of README.linux, if there's a standard convention for this do that).

You can email me through github, yes.
